CREATE TABLE IF NOT EXISTS videos(
    id INTEGER PRIMARY KEY,
    series_id INTEGER NOT NULL,
    path TEXT UNIQUE NOT NULL,
    FOREIGN KEY (series_id) REFERENCES series(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS SERIES(
    id INTEGER PRIMARY KEY,
    title TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS MARKINGS(
    id INTEGER PRIMARY KEY,
    video_id INTEGER NOT NULL,
    description TEXT,
    start_timestamp INTEGER NOT NULL,
    -- NULL represents "till the end of the video"
    end_timestamp INTEGER,
    FOREIGN KEY (video_id) REFERENCES videos(id) ON UPDATE CASCADE ON DELETE CASCADE
);
